name: youtube_clone
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0-177.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bottom_sheet: ^4.0.4
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.0.0
  ffmpeg_kit_flutter: ^6.0.3
  fraction: ^5.0.2
  firebase_storage: ^12.0.0
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1
  image_picker_android: ^0.8.12+1
  path: ^1.9.0
  intl: ^0.19.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  uuid: ^4.4.0
  video_player: ^2.8.6
  video_editor: ^3.0.0
  timeago: ^3.6.1
  google_nav_bar: ^5.0.6
  flutter_staggered_grid_view: ^0.7.0
  flutter_riverpod: ^2.5.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700